# General configuration settings
title: Jeff’s Blog
tagline: An experiment in the blogisphere
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: https://jefx07.github.io

# About/contact (for atom news feed)
author:
  name:  # Required (leave blank to use website title)
  email: # (optional)

# Enter your Google Analytics tracking ID (e.g. UA-000000-01) to activate the tracking code
google_analytics_id: UA-87931263-1

# Use the following plug-ins
gems:
  - jekyll-sitemap

# Permalinks
permalink: /:year/:title/

# Exclude from site build
exclude:
  - README.md
  - CNAME

# Processor options
kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed
