# General configuration settings
title: Jeff's Blog
tagline: Just another Jekyll blog
description: "Just a blog about things I've learned and life in general."
baseurl: ""
url: https://jefx07.github.io

# About/contact (for atom news feed)
author:
  name:  # Required (leave blank to use website title)
  email: # (optional)

# Enter your Google Analytics tracking ID (e.g. UA-000000-01) to activate the tracking code
google_analytics_id: G-MPVD86GHMF
google_verify:

# Use the following plug-ins
plugins:
  - jekyll-sitemap

# Permalinks
permalink: /blog/:year/:month/:title/

# Exclude from site build
exclude:
  - README.md
  - CNAME
  - node_modules
  - package.json
  - package-lock.json

# Processor options
kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed
