# General configuration settings
title: Jeff's Blog
tagline: The place to be
description: "Just a blog about things, and everything you need to know."
baseurl: ""
url: https://jefx07.github.io

# About/contact (for atom news feed)
author:
  name:  # Required (leave blank to use website title)
  email: # (optional)

# Enter your Google Analytics tracking ID (e.g. UA-000000-01) to activate the tracking code
google_analytics_id: UA-87931263-1
google_verify: HXOLJ6CE_xR58FLhhX2Jwkh8dRdxVXV3Yqui4WCmLs0

# Use the following plug-ins
plugins:
  - jekyll-sitemap

# Permalinks
permalink: /blog/:year/:month/:title/

# Exclude from site build
exclude:
  - README.md
  - CNAME
  - package.json
  - package-lock.json

# Processor options
kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed
